### ISSUE TITLE
NoneType exception in get_mentions()

### ISSUE THREAD

**Issue by seLain** [seLain/MissAchieve#1]
Traceback (most recent call last):
  File "C:\py36_venv\MissAchieve\lib\site-packages\mattermost_bot\dispatcher.py", line 75, in dispatch_msg
    func(Message(self._client, msg, self._pool), *args)
  File "C:\GitHub\MissAchieve\bots\mm_bot_plugins\achievements.py", line 13, in listen_to_all
    mentions_mission(message)
  File "C:\GitHub\MissAchieve\bots\mm_bot_plugins\achievements.py", line 44, in mentions_mission
    mentions = len(message.get_mentions())
TypeError: object of type 'NoneType' has no len()

**Comment by seLain** [comment]
fixed. if message.get_mentions() == None, mentions = 0 else  len(message.get_mentions())
